#!/bin/bash
# Install dependencies for Chromium
playwright install-deps

# Force install Chromium into the current working directory's .playwright folder
PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium
