#!/bin/bash
# Install Chromium dependencies
playwright install-deps

# Force install Chromium into the current directory (bundled into app image)
export PLAYWRIGHT_BROWSERS_PATH=$(pwd)/.playwright
mkdir -p $PLAYWRIGHT_BROWSERS_PATH
playwright install chromium
